### ISSUE TITLE
Make all user case

### ISSUE THREAD

**Issue by tmhhh** [tmhhh/ProjectSE#1]

**Comment by nguyendactin** [comment]
https://github.com/tmhhh/ProjectSE/blob/main/NDT%20All%20user%20case.docx
My document for this task

**Comment by tmhhh** [comment]
My document for this task https://github.com/tmhhh/ProjectSE/blob/main/Hoang%20All%20user%20case.docx

**Comment by khanghoang1702** [comment]
allUserCase-Khang done link: https://github.com/tmhhh/ProjectSE.git
